import nltk
from nltk.corpus import stopwords
import re
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

import json

nltk.download("stopwords")
nltk.download("punkt")

nltk.download("wordnet")

# --------------------------------

with open("FinalDataset.json", "r") as fp:
    df = json.load(fp)


def remove_contradictions(text):
    if "n't" in text:
        text = text.replace("n't", " not")

    contractions = {
        "ai\snot": "am not",
        "wo\snot": "will not",
        "would\snot": "would not",
        "should\snot": "should not",
        "isn\snot": "is not",
        "aren\snot": "are not",
        "wasn\snot": "was not",
        "weren\snot": "were not",
        "haven\snot": "have not",
        "hasn\snot": "has not",
        "hadn\snot": "had not",
        "don\snot": "do not",
        "doesn\snot": "does not",
        "didn\snot": "did not",
        "can\snot": "can not",
        "cannot": "can not",
        "couldn\snot": "could not",
        "shouldn\snot": "should not",
        "mightn\snot": "might not",
        "mustn\snot": "must not",
        "shan\snot": "shall not",
        "won\snot": "will not",
        "ain\snot": "am not",
        "I\sam": "I am",
        "you\sare": "you are",
        "he\sis": "he is",
        "she\sis": "she is",
        "it\sis": "it is",
        "we\sare": "we are",
        "they\sare": "they are",
        "I\swould": "I would",
        "you\swould": "you would",
        "he\swould": "he would",
        "she\swould": "she would",
        "it\swould": "it would",
        "we\swould": "we would",
        "they\swould": "they would",
        "I\scould": "I could",
        "you\scould": "you could",
        "he\scould": "he could",
        "she\scould": "she could",
        "it\scould": "it could",
        "we\scould": "we could",
        "they\scould": "they could",
        "I\shave": "I have",
        "you\shave": "you have",
        "he\shas": "he has",
        "she\shas": "she has",
        "it\shas": "it has",
        "we\shave": "we have",
        "they\shave": "they have",
        "I\swill": "I will",
        "you\swill": "you will",
        "he\swill": "he will",
        "she\swill": "she will",
        "it\swill": "it will",
        "we\swill": "we will",
        "they\swill": "they will",
        "I\smust": "I must",
        "you\smust": "you must",
        "he\smust": "he must",
        "she\smust": "she must",
        "it\smust": "it must",
        "we\smust": "we must",
        "they\smust": "they must",
        "I\sshall": "I shall",
        "you\sshall": "you shall",
        "he\sshall": "he shall",
        "she\sshall": "she shall",
        "it\sshall": "it shall",
        "we\sshall": "we shall",
        "they\sshall": "they shall",
        # Add more contractions as needed
        "haven\s't": "have not",
        "hasn\s't": "has not",
        "hadn\s't": "had not",
        "don\s't": "do not",
        "doesn\s't": "does not",
        "didn\s't": "did not",
        "can\s't": "can not",
        "cannot": "can not",
        "couldn\s't": "could not",
        "shouldn\s't": "should not",
        "mightn\s't": "might not",
        "mustn\s't": "must not",
        "shan\s't": "shall not",
        "won\s't": "will not",
        "ain\s't": "am not",
        "aren\s't": "are not",
        "wasn\s't": "was not",
        "weren\s't": "were not",
        "I\sdidn't": "I did not",
        "you\sdidn't": "you did not",
        "he\sdidn't": "he did not",
        "she\sdidn't": "she did not",
        "it\sdidn't": "it did not",
        "we\sdidn't": "we did not",
        "they\sdidn't": "they did not",
        "I\scannot": "I can not",
        "you\scannot": "you can not",
        "he\scannot": "he can not",
        "she\scannot": "she can not",
        "it\scannot": "it can not",
        "we\scannot": "we can not",
        "they\scannot": "they can not",
        "I\swon't": "I will not",
        "you\swon't": "you will not",
        "he\swon't": "he will not",
        "she\swon't": "she will not",
        "it\swon't": "it will not",
        "we\swon't": "we will not",
        "they\swon't": "they will not",
        "I\shasn't": "I has not",
        "you\shasn't": "you has not",
        "he\shasn't": "he has not",
        "she\shasn't": "she has not",
        "it\shasn't": "it has not",
        "we\shasn't": "we has not",
        "they\shasn't": "they has not",
        # Add more contractions as needed
    }

    for pattern, replacement in contractions.items():
        text = re.sub(pattern, replacement, text)

    return text


def removing_not(text):
    d = {
        "not sad": "Happy",
        "not bad": "Happy",
        "not boring": "Happy",
        "not wrong": "Happy",
        "not bored": "Happy",
        "not jealous": "Happy",
        "not happy": "Sad",
        "not well": "Sad",
        "not suitable": "Angry",
        "not right": "Angry",
        "not good": "Sad",
        "not excited": "Angry",
        "not funny ": "Sad",
        "not kind": "Sad",
        "not proud": "Angry",
        "not cool": "Angry",
        "not funny": "Angry",
        "not kind": "Angry",
        "not open": "Angry",
        "not safe": "Fear",
        "not enough": "Empty",
        "not know": "Sad",
        "not knowing": "Sad",
        "not believe": "Angry",
        "not believing": "Angry",
        "not understand": "Sad",
        "not understanding": "Sad",
        "no doubt": "Happy",
        "not think": "Sad",
        "not thinking": "Sad",
        "not recognise": "Sad",
        "not recognising": "Sad",
        "not forget": "Angry",
        "not forgetting": "Angry",
        "not remember": "Sad",
        "not remembering": "Sad",
        "not imagine": "Sad",
        "not imagining": "Sad",
        "not mean": "Sad",
        "not meaning": "Sad",
        "not agree": "Angry",
        "not agreeing": "Sad",
        "not disagree": "Happy",
        "not disagreeing": "Happy",
        "not deny": "Sad",
        "not denying": "Sad",
        "not promise": "Angry",
        "not promising": "Angry",
        "not satisfy": "Sad",
        "not satisfying": "Sad",
        "not realise": "Sad",
        "not realising": "Sad",
        "not appear": "Angry",
        "not appearing": "Angry",
        "not please": "Sad",
        "not pleasing": "Sad",
        "not impress": "Sad",
        "not impressing": "Sad",
        "not surprise": "Sad",
        "not surprising": "Sad",
        "not concern": "Sad",
        "not concerning": "Sad",
        "not have": "Sad",
        "not having": "Sad",
        "not own": "Sad",
        "not owning": "Sad",
        "not possess": "Sad",
        "not possessing": "Sad",
        "not lack": "Sad",
        "not lacking": "Sad",
        "not consist": "Sad",
        "not consisting": "Sad",
        "not involve": "Sad",
        "not involving": "Sad",
        "not include": "Sad",
        "not including": "Sad",
        "not contain": "Sad",
        "not containing": "Sad",
        "not love": "Sad",
        "not like": "Angry",
        "not hate": "Happy",
        "not hating": "Happy",
        "not adore": "Sad",
        "not adoring": "Sad",
        "not prefer": "Sad",
        "not preferring": "Sad",
        "not care": "Angry",
        "not mind": "Angry",
        "not minding": "Sad",
        "not want": "Angry",
        "not wanting": "Sad",
        "not need": "Angry",
        "not needing": "Angry",
        "not desire": "Sad",
        "not desiring": "Sad",
        "not wish": "Sad",
        "not wishing": "Sad",
        "not hope": "Sad",
        "not hoping": "Sad",
        "not appreciate": "Sad",
        "not appreciating": "Sad",
        "not value": "Sad",
        "not valuing": "Sad",
        "not owe": "Sad",
        "not owing": "Sad",
        "not seem": "Sad",
        "not seeming": "Sad",
        "not fit": "Sad",
        "not fitting": "Sad",
        "not depend": "Sad",
        "not depending": "Sad",
        "not matter": "Sad",
        "not afford": "Sad",
        "not affording": "Sad",
        "not aim": "Sad",
        "not aiming": "Sad",
        "not attempt": "Angry",
        "not attempting": "Angry",
        "not ask": "Angry",
        "not asking": "Angry",
        "not arrange": "Angry",
        "not arranging": "Angry",
        "not beg": "Angry",
        "not begging": "Angry",
        "not begin": "Angry",
        "not beginning": "Angry",
        "not caring": "Angry",
        "not choose": "Angry",
        "not choosing": "Angry",
        "not claim": "Angry",
        "not claiming": "Angry",
        "not consent": "Angry",
        "not consenting": "Angry",
        "not continue": "Angry",
        "not continuing": "Angry",
        "not dare": "Angry",
        "not daring": "Angry",
        "not decide": "Sad",
        "not deciding": "Sad",
        "not demand": "Angry",
        "not demanding": "Angry",
        "not deserve": "Angry",
        "not deserving": "Angry",
        "not expect": "Angry",
        "not expecting": "Angry",
        "not fail": "Happy",
        "not failing": "Happy",
        "not get": "Sad",
        "not getting": "Sad",
        "not hesitate": "Sad",
        "not hesitating": "Sad",
        "not hurry": "Happy",
        "not hurrying": "Happy",
        "not intend": "Sad",
        "not intending": "Sad",
        "not learn": "Angry",
        "not learning": "Angry",
        "not liking": "Angry",
        "not loving": "Sad",
        "not manage": "Angry",
        "not managing": "Angry",
        "not neglect": "Sad",
        "not neglecting": "Sad",
        "not offer": "Angry",
        "not offering": "Angry",
        "not plan": "Angry",
        "not planing": "Angry",
        "not prepare": "Angry",
        "not preparing": "Angry",
        "not pretend": "Angry",
        "not pretending": "Angry",
        "not proceed": "Angry",
        "not proceeding": "Angry",
        "not propose": "Angry",
        "not proposing": "Sad",
        "not refuse": "Sad",
        "not refusing": "Sad",
        "not start": "Sad",
        "not starting": "Sad",
        "not stop": "Happy",
        "not stopping": "Happy",
        "not struggle": "Angry",
        "not struggling": "Angry",
        "not swear": "Angry",
        "not swearing": "Angry",
        "not threaten": "Happy",
        "not threatening": "Happy",
        "not try": "Angry",
        "not trying": "Angry",
        "not volunteer": "Angry",
        "not volunteering": "Angry",
        "not wait": "Angry",
        "not waiting": "Angry",
        "not feel": "Sad",
        "not feeling": "Sad",
        "not able": "Sad",
        "not do": "Sad",
        "not apologize": "Sad",
        "not apologizing": "Sad",
        "not forgive": "Angry",
        "not forgiving": "Angry",
        "not trust": "Angry",
        "not trusting": "Angry",
        "not regret": "Angry",
        "not regretting": "Angry",
        "not rejoice": "Sad",
        "not rejoicing": "Sad",
        "not admire": "Sad",
        "not admiring": "Sad",
        "not compliment": "Sad",
        "not complimenting": "Sad",
        "not criticize": "Happy",
        "not criticizing": "Happy",
        "not encourage": "Angry",
        "not encouraging": "Angry",
        "not insult": "Sad",
        "not insulting": "Sad",
        "not praise": "Angry",
        "not praising": "Angry",
        "not support": "Angry",
        "not supporting": "Angry",
        "not blame": "Sad",
        "not blaming": "Sad",
        "not defend": "Sad",
        "not defending": "Sad",
        "not appreciate": "Sad",
        "not appreciating": "Sad",
        "not enjoy": "Sad",
        "not enjoying": "Sad",
        "not like": "Angry",
        "not liking": "Angry",
        "not love": "Sad",
        "not loving": "Sad",
        "not prefer": "Sad",
        "not preferring": "Sad",
        "not want": "Angry",
        "not wanting": "Sad",
        "not believe": "Angry",
        "not believing": "Angry",
        "not doubt": "Happy",
        "not doubting": "Happy",
        "not imagine": "Sad",
        "not imagining": "Sad",
        "not realize": "Sad",
        "not realizing": "Sad",
        "not remember": "Sad",
        "not remembering": "Sad",
        "not recognize": "Sad",
        "not recognizing": "Sad",
        "not consider": "Sad",
        "not considering": "Sad",
        "not think": "Sad",
        "not thinking": "Sad",
        "not forget": "Angry",
        "not forgetting": "Angry",
        "not ignore": "Angry",
        "not ignoring": "Angry",
        "not overlook": "Angry",
        "not overlooking": "Angry",
        "not understand": "Sad",
        "not understanding": "Sad",
        "not hear": "Angry",
        "not hearing": "Angry",
        "not listen": "Angry",
        "not listening": "Angry",
        "not look": "Angry",
        "not looking": "Angry",
        "not smell": "Angry",
        "not smelling": "Angry",
        "not taste": "Angry",
        "not tasting": "Angry",
        "not touch": "Angry",
        "not touching": "Angry",
        "not feel": "Sad",
        "not feeling": "Sad",
        "not sense": "Sad",
        "not sensing": "Sad",
        "not suppose": "Angry",
        "not supposing": "Angry",
        "not expect": "Angry",
        "not expecting": "Angry",
        "not wait": "Angry",
        "not waiting": "Angry",
        "not long": "Angry",
        "not longing": "Angry",
        "not yearn": "Angry",
        "not yearning": "Angry",
        "not wish": "Sad",
        "not wishing": "Sad",
        "not hope": "Sad",
        "not hoping": "Sad",
        "not desire": "Sad",
        "not desiring": "Sad",
        "not miss": "Angry",
        "not missing": "Angry",
        "not need": "Angry",
        "not needing": "Angry",
        "not want": "Angry",
        "not wanting": "Sad",
        "not require": "Angry",
        "not requiring": "Angry",
        "not demand": "Angry",
        "not demanding": "Angry",
        "not insist": "Angry",
        "not insisting": "Angry",
        "not force": "Angry",
        "not forcing": "Angry",
        "not push": "Angry",
        "not pushing": "Angry",
        "not pull": "Angry",
        "not pulling": "Angry",
        "not drag": "Angry",
        "not dragging": "Angry",
        "not carry": "Angry",
        "not carrying": "Angry",
        "not lift": "Angry",
        "not lifting": "Angry",
        "not drop": "Angry",
        "not dropping": "Angry",
        "not throw": "Angry",
        "not throwing": "Angry",
        "not catch": "Angry",
        "not catching": "Angry",
        "not capture": "Angry",
        "not capturing": "Angry",
        "not grab": "Angry",
        "not grabbing": "Angry",
        "not touch": "Angry",
        "not touching": "Angry",
        "not reach": "Angry",
        "not reaching": "Angry",
        "not approach": "Angry",
        "not approaching": "Angry",
        "not avoid": "Angry",
        "not avoiding": "Angry",
        "not evade": "Angry",
        "not evading": "Angry",
        "not elude": "Angry",
        "not eluding": "Angry",
        "not escape": "Angry",
        "not escaping": "Angry",
        "not run": "Angry",
        "not running": "Angry",
        "not jog": "Angry",
        "not jogging": "Angry",
        "not walk": "Angry",
        "not walking": "Angry",
        "not crawl": "Angry",
        "not crawling": "Angry",
        "not sneak": "Angry",
        "not sneaking": "Angry",
        "not tiptoe": "Angry",
        "not tiptoeing": "Angry",
        "not dance": "Angry",
        "not dancing": "Angry",
        "not stomp": "Angry",
        "not stomping": "Angry",
        "not shake": "Angry",
        "not shaking": "Angry",
        "not tremble": "Angry",
        "not trembling": "Angry",
        "not shiver": "Angry",
        "not shivering": "Angry",
        "not quiver": "Angry",
        "not quivering": "Angry",
        "not vibrate": "Angry",
        "not vibrating": "Angry",
        "not pulsate": "Angry",
        "not pulsating": "Angry",
        "not throb": "Angry",
        "not throbbing": "Angry",
        "not beat": "Angry",
        "not beating": "Angry",
        "not palpitate": "Angry",
        "not palpitating": "Angry",
        "not pump": "Angry",
        "not pumping": "Angry",
        "not glide": "Angry",
        "not gliding": "Angry",
        "not slide": "Angry",
        "not sliding": "Angry",
        "not slip": "Angry",
        "not slipping": "Angry",
        "not skid": "Angry",
    }

    f = re.findall("not\s\w+", text)
    for i in f:
        try:
            text = text.replace(i, d[i])
        except:
            pass
    text = text.lower()
    return text


def removing_shortcuts(text):
    full_words = []
    shortcuts = {
        "u": "you",
        "y": "why",
        "r": "are",
        "doin": "doing",
        "hw": "how",
        "k": "okay",
        "m": "am",
        "b4": "before",
        "idc": "i do not care",
        "ty": "thank you",
        "wlcm": "welcome",
        "bc": "because",
        "<3": "love",
        "xoxo": "love",
        "ttyl": "talk to you later",
        "gr8": "great",
        "bday": "birthday",
        "awsm": "awesome",
        "gud": "good",
        "h8": "hate",
        "lv": "love",
        "dm": "direct message",
        "rt": "retweet",
        "wtf": "hate",
        "idgaf": "hate",
        "irl": "in real life",
        "yolo": "you only live once",
        "don't": "do not",
        "g8": "great",
        "won't": "will not",
        "tbh": "to be honest",
        "caj": "casual",
        "Ikr": "I know, right?",
        "omw": "on my way",
        "ofc": "of course",
        "Idc": "I don't care",
        "Irl": "In real life",
        "tbf": "To be fair",
        "obvs": "obviously",
        "v": "very",
        "atm": "at the moment",
        "col": "crying out loud",
        "gbu": "god bless you",
        "gby": "god bless you",
        "gotcha": "I got you",
        "hehe": "laughing",
        "haha": "laughing",
        "hf": "have fun",
        "hry": "hurry",
        "hw": "hardwork",
        "idc": "i don’t care",
        "ikr": "i know right",
        "k": "ok",
        "lmao": "laughing my ass off",
        "lol": "laughing out loud",
        "n1": "nice one",
        "na": "not available",
        "qt": "cutie",
        "qtpi": "cutie pie",
        "rip": "rest in peace",
        "sry": "sorry",
        "tc": "take care",
        "thnks": "thanks",
        "thx": "thanks",
        "thnk": "thanks",
        "ttyl": "talk to you later",
        "txt": "text",
        "ugh": "disgusted",
        "w8": "wait",
        "not sad": "happy",
    }
    for token in text:
        if token in shortcuts.keys():
            token = shortcuts[token]
        full_words.append(token)
    text = " ".join(full_words)
    return text


def removing_stopwords(text):
    stop_words = set(stopwords.words("english"))
    stop = [x.lower() for x in stop_words]
    return [word for word in text if not word in stop]


def lemmatization(words_big):
    lemma = WordNetLemmatizer()
    stemmed_words = [lemma.lemmatize(word, "v") for word in words_big]
    stemmed_words = [lemma.lemmatize(word, "n") for word in stemmed_words]
    return " ".join(stemmed_words)


def cleaning(text):
    text = text.lower()
    text = re.sub(r"http\S+|www.\S+", "", text)
    text = remove_contradictions(text)
    text = removing_not(text)
    text = text.split()
    text = removing_shortcuts(text)
    text = " ".join([i for i in text.split() if not i.isdigit()])
    text = word_tokenize(text)
    words_alpha = removing_stopwords(text)
    words_big = [word for word in words_alpha if len(word) > 2]
    clean_text = lemmatization(words_big)
    clean_text = clean_text.replace("   ", " ")
    clean_text = clean_text.replace("  ", " ")
    return clean_text


def get_emotion(input):
    text = cleaning(input).split()
    emotion_values = []
    emotions = {"joy": 0,"anger": 0,"surprise": 0,"sadness": 0,"fear": 0,"anticipation": 0,"disgust": 0,"negative": 0,"positive": 0,"trust": 0,}
    y = 0
    try:
        for word in text:
            if word in df.keys():
                for emotion in df[word]:
                    emotions[emotion] += 1

        if sum(emotions.values()) == 0:
            return None
        for i in emotions:
            emotion_values.append(round((emotions[i] / sum(emotions.values())), 2))
        for j in emotions:
            emotions[j] = emotion_values[y]
            y += 1

        return emotions
    except:
        print("Get_emotion error")


def maxEmotion(emotions):
    if emotions is None:
        return [], []
    else:
        emotions["surprise"] += emotions["anticipation"]
        emotions["anger"] += emotions["disgust"]
        emotions["sadness"] += emotions["negative"]
        emotions["joy"] += emotions["positive"]
        emotions["joy"] += emotions["trust"]
        del emotions["anticipation"]
        del emotions["disgust"]
        del emotions["negative"]
        del emotions["positive"]
        del emotions["trust"]
        max_value = max(emotions.values())
        MainEmotion = [key for key, value in emotions.items() if value == max_value]
        return MainEmotion, emotions
